server:
  port: 9090
spring:
  application:
    name: GestionRH
  datasource:
    url: jdbc:postgresql://localhost:5432/sistemultinivel
    username: stevencalde
    password: 'usbcali123'
    driver-class-name: org.postgresql.Driver
